# generated by datamodel-codegen:
#   filename:  blender_asset_library_openapi.yaml
#   timestamp: 2025-03-31T16:17:06+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Contact(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    url: str
    email: Optional[str] = None


class AssetIDType(Enum):
    brush = "brush"
    action = "action"
    collection = "collection"
    object = "object"
    nodetree = "nodetree"
    material = "material"
    world = "world"


class AssetMetadata(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    catalog: Optional[str] = Field(
        None,
        description="The catalog path that contains this asset.\nTODO: we could also put the UUID here, making it easier if we ever need to create a per-blendfile .cats.txt file.\n",
    )
    tags: Optional[list[str]] = Field(None, min_length=1)
    author: Optional[str] = None
    description: Optional[str] = None
    license: Optional[str] = None
    copyright: Optional[str] = None


class Catalog(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    path: str
    uuids: list[UUID] = Field(..., min_length=1)


class AssetLibraryMeta(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    api_version: Optional[int] = Field(
        None,
        description="API version of this asset library. This is reflected in the URLs of all OpenAPI operations except the one to get this metadata.",
    )
    name: str = Field(..., description="Name of this asset library.")
    contact: Optional[Contact] = None


class AssetLibraryIndex(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    schema_version: str = Field(
        ...,
        description="Version number of the used schema. This should be the same as the version of this OpenAPI definition, as described in its 'info.version' field.\n",
    )
    asset_size_bytes: int
    asset_count: Optional[int] = Field(
        None,
        description="Total number of assets in this index. This is the sum of all `asset_count` fields of each page.\n",
    )
    page_count: Optional[int] = Field(None, description="Number of pages of assets in this index.")
    catalogs: Optional[list[Catalog]] = None


class Asset(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., description="Name of the Blender data-block.")
    id_type: AssetIDType
    blender_version_min: Optional[str] = Field(
        None,
        description="Minimal version of Blender required to use this asset. Should be a semantic version, which may be shortened ('3.1' matches any '3.1.x' version).\n",
    )
    archive_url: str = Field(
        ...,
        description="URL where a blend file containing this asset can be downloaded. If the URL is relative, it is to be interpreted as relative to the library's root URL.\n",
    )
    archive_size_in_bytes: int
    archive_hash: str = Field(
        ...,
        description='Hash of the file at \'archive_url\'. This should be in the format "HASHTYPE:HASH-AS-HEX". Currently only the "SHA256" hash type is supported.\n',
    )
    thumbnail_url: Optional[str] = Field(
        None,
        description="URL where a blend file containing this asset can be downloaded. If the URL is relative, it is to be interpreted as relative to the library's root URL.\n",
    )
    meta: Optional[AssetMetadata] = None


class AssetLibraryIndexPage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    asset_count: int = Field(..., description="Number of assets in this page.")
    assets: list[Asset]
