/* SPDX-FileCopyrightText: 2011-2025 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

/* A basic perspective camera. */

shader camera(float focal_length = 90.0,
              output point pos = 0.0,
              output vector dir = 0.0,
              output color T = 1.0)
{
  vector sensor_size;
  getattribute("cam:sensor_size", sensor_size);

  point Pcam = camera_shader_raster_position() - point(0.5);
  Pcam *= sensor_size / focal_length;
  dir = normalize(vector(Pcam.x, Pcam.y, 1.0));
}
