/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "stdcycles.h"

// TODO (OpenPBR): implement the OpenPBR OSL shader

shader node_open_pbr_bsdf(color Color = 0.8,
                         float Roughness = 0.0,
                         normal Normal = N,
                         output closure color BSDF = 0)
{
  if (Roughness < 1e-5)
    BSDF = Color * diffuse(Normal);
  else
    BSDF = oren_nayar_diffuse_bsdf(Normal, clamp(Color, 0.0, 1.0), Roughness);
}
