/* SPDX-FileCopyrightText: 2011-2026 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "stdcycles.h"

shader node_curvature(int samples = 16,
                      float Radius = 0.01,
                      int only_local = 0,
                      output float Curvature = 0.5)
{
  /* Abuse texture call with special @curvature token. */
  Curvature = texture("@curvature", samples, Radius, 0, only_local, 0, 0);
}
