/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "stdcycles.h"

shader node_raycast(point Position = P,
                    normal Direction = N,
                    float Length = 1.0,
                    int only_local = 0,
                    output float IsHit = 0.0,
                    output point HitPosition = point(0.0, 0.0, 0.0),
                    output float HitDistance = Length)
{
  /* Abuse texture call with special @raycast token. */
  float result = texture("@raycast",
                         Position[0],
                         Position[1],
                         Position[2],
                         Direction[0],
                         Direction[1],
                         Direction[2],
                         "sblur",
                         Length,
                         "tblur",
                         only_local);

  if (result >= 0.0) {
    IsHit = 1.0;
    HitDistance = result;
    HitPosition = Position + Direction * HitDistance;
  }
}
