/* SPDX-FileCopyrightText: 2011-2022 Blender Foundation
 *
 * SPDX-License-Identifier: Apache-2.0 */

#include "node_scatter_mie.h"
#include "stdcycles.h"

shader node_scatter_volume(string phase = "Henyey-Greenstein",
                           color Color = color(0.8, 0.8, 0.8),
                           float Density = 1.0,
                           float Anisotropy = 0.0,
                           float IOR = 1.33,
                           float Backscatter = 0.1,
                           float Alpha = 0.5,
                           float Diameter = 20.0,
                           output closure color Volume = 0)
{
  closure color scatter = 0;
  if (phase == "Fournier-Forand") {
    scatter = fournier_forand(Backscatter, IOR);
  }
  else if (phase == "Draine") {
    scatter = draine(Anisotropy, Alpha);
  }
  else if (phase == "Rayleigh") {
    scatter = rayleigh();
  }
  else if (phase == "Mie") {
    /* Approximation of Mie phase function for water droplets using a mix of Draine and H-G.
     * See `kernel/svm/closure.h` for details. */
    MieParameters param = phase_mie_fitted_parameters(Diameter);
    scatter = mix(henyey_greenstein(param.g_HG), draine(param.g_D, param.alpha), param.mixture);
  }
  else {
    scatter = henyey_greenstein(Anisotropy);
  }

  Volume = (Color * max(Density, 0.0)) * scatter;
}
