# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Generated by datamodel-codegen:
#   source filename:  blender_releases_openapi.yaml

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class CycleType(StrEnum):
    """Release Cycle."""

    release = "release"
    alpha = "alpha"
    beta = "beta"
    rc = "rc"


type TimeStamp = str


@dataclass
class VersionUpdate:
    """Available Blender Release for download."""

    build_size: int
    """Size in bytes of the download files."""

    checksum_hash: str
    """SHA256 hash value of the download files."""

    commit_hash: str
    """Identifier of the commit used to build this version."""

    description: str
    """Short description of new features in this version."""

    download_url: str
    """URL where this version can can be downloaded."""

    cycle: CycleType
    """Release cycle."""

    is_lts: bool
    """Checks if this version have Long-Term Support."""

    platform: str
    """Target platform for this version."""

    release_notes_url: str
    """URL to a more detailed release notes page."""

    timestamp: TimeStamp
    """Time when this version became available."""

    version: str
    """Version identifier of this release."""
