/*
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include "BLI_math_geom.h"

#include "BKE_mesh.h"

#include "GEO_mesh_loop_cut.hh"

#include "node_geometry_util.hh"

namespace blender::nodes::node_geo_loop_cut_cc {

class PointsFieldContext : public FieldContext {
 private:
  int points_num_;

 public:
  PointsFieldContext(const int points_num) : points_num_(points_num) {}

  int64_t points_num() const
  {
    return points_num_;
  }

  GVArray get_varray_for_input(const FieldInput &field_input,
                               const IndexMask &mask,
                               ResourceScope & /*scope*/) const
  {
    const bke::IDAttributeFieldInput *id_field_input =
        dynamic_cast<const bke::IDAttributeFieldInput *>(&field_input);

    const fn::IndexFieldInput *index_field_input = dynamic_cast<const fn::IndexFieldInput *>(
        &field_input);

    if (id_field_input == nullptr && index_field_input == nullptr) {
      return {};
    }

    return fn::IndexFieldInput::get_index_varray(mask);
  }
};

/* Node arg names: */
constexpr char AFFECTED[10] = "Selection";
constexpr char NUM_CUTS[15] = "Number of Cuts";

constexpr char EDGE_INDEX[11] = "Edge Index";
constexpr char CUT_FACTOR[7] = "Factor";

constexpr char LOOP_SELECTION[15] = "Loop Selection";

/*
 * Mesh
 */
static void geo_node_declare(NodeDeclarationBuilder &b)
{
  b.add_input<decl::Geometry>("Mesh").supported_type(GeometryComponent::Type::Mesh);

  b.add_input<decl::Bool>(AFFECTED).default_value(true).field_on_all().hide_value();
  b.add_input<decl::Int>(NUM_CUTS).default_value(0);
  b.add_input<decl::Int>(EDGE_INDEX).default_value(false).field_on_all().hide_value();
  b.add_input<decl::Float>(CUT_FACTOR).default_value(0).field_on_all().hide_value();

  b.add_output<decl::Geometry>(N_("Mesh")).propagate_all();
  b.add_output<decl::Bool>(LOOP_SELECTION)
      .field_on_all()
      .description("Edge selection for edges generated by and part of the loop cut");
}

static void node_geo_exec(GeoNodeExecParams params)
{
  GeometrySet geometry_set = params.extract_input<GeometrySet>("Mesh");
  const int num_cuts = params.extract_input<int>(NUM_CUTS);

  geometry_set.modify_geometry_sets([&](GeometrySet &geometry_set) {
    const Mesh *mesh = geometry_set.get_mesh();
    if (mesh == nullptr || num_cuts == 0) {
      return;
    }

    PointsFieldContext context{num_cuts};
    fn::FieldEvaluator evaluator{context, num_cuts};
    evaluator.add(params.get_input<Field<int>>(EDGE_INDEX));
    evaluator.add(params.get_input<Field<float>>(CUT_FACTOR));
    evaluator.evaluate();

    const VArraySpan<int> cut_edge_index = evaluator.get_evaluated<int>(0);
    const VArraySpan<float> cut_factors = evaluator.get_evaluated<float>(1);

    Array<int> accumulated_num_cuts(mesh->edges_num + 1);
    OffsetIndices<int> loop_cut_offsets(accumulated_num_cuts);
    accumulated_num_cuts.fill(0);

    /* Order/sort the cut factors. */
    int num_edges_cut = 0;
    // TODO: SORT indices and remove any invalid rather then clamp?
    for (int index : cut_edge_index) {
      index = clamp_i(index, 0, mesh->edges_num - 1);
      num_edges_cut += accumulated_num_cuts[index + 1] == 0;
      accumulated_num_cuts[index + 1]++;
    }

    Vector<int> cut_mask;
    cut_mask.reserve(num_edges_cut);
    for (const int64_t index : loop_cut_offsets.index_range()) {
      if (accumulated_num_cuts[index + 1] != 0) {
        cut_mask.append(index);
      }
      accumulated_num_cuts[index + 1] += accumulated_num_cuts[index]; /* accumulate */
    }
    BLI_assert(cut_mask.size() == num_edges_cut);

    Array<int> cut_count(mesh->edges_num);
    cut_count.fill(0);

    Array<float> loop_cut_factors(cut_edge_index.size());
    for (const int64_t index : cut_edge_index.index_range()) {
      const int64_t loop_index = clamp_i(cut_edge_index[index], 0, mesh->edges_num - 1);
      loop_cut_factors[loop_cut_offsets[loop_index].start() + cut_count[loop_index]] = clamp_f(
          cut_factors[index], 0.0f, 1.0f);
      cut_count[loop_index]++;
    }

    /* Create a filtered mask if necessary... */
    IndexMaskMemory memory;
    IndexMask loop_cut_mask = IndexMask::from_indices<int>(cut_mask, memory);

    const bke::MeshFieldContext face_context{*mesh, AttrDomain::Face};
    fn::FieldEvaluator affected_evaluator{face_context, mesh->faces_num};
    affected_evaluator.add(params.get_input<Field<bool>>(AFFECTED));
    affected_evaluator.evaluate();

    const VArraySpan<bool> affected = affected_evaluator.get_evaluated<bool>(0);

    geometry::LoopCutAttributeOutputs attribute_outputs;
    attribute_outputs.loop_cut_edge_selection = params.get_output_anonymous_attribute_id_if_needed(
        LOOP_SELECTION);

    std::optional<Mesh *> result = geometry::loop_cut(*mesh,
                                                      affected,
                                                      loop_cut_mask,
                                                      loop_cut_offsets,
                                                      loop_cut_factors,
                                                      attribute_outputs,
                                                      params.get_attribute_filter("Mesh"));

    if (result) {
      geometry_set.replace_mesh(*result);
    }
  });

  params.set_output("Mesh", std::move(geometry_set));
}

static void node_register()
{
  static blender::bke::bNodeType ntype;

  geo_node_type_base(&ntype, "GeometryNodeLoopCut");
  ntype.ui_name = "Loop Cut";
  ntype.ui_description =
      "Insert edge loop(s) in the face loops traversed from the starting points defined by the face loop edge selection";
  ntype.nclass = NODE_CLASS_GEOMETRY;
  ntype.declare = geo_node_declare;
  ntype.geometry_node_execute = node_geo_exec;
  // ntype.gather_link_search_ops = node_gather_link_searches;
  blender::bke::node_register_type(ntype);
}

NOD_REGISTER_NODE(node_register)

}  // namespace blender::nodes::node_geo_loop_cut_cc
