# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Generated by datamodel-codegen:
#   source filename:  blender_manifest_openapi.yaml

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class Type(StrEnum):
    """Extension type."""

    add_on = "add-on"
    theme = "theme"
    asset_library = "asset-library"


type Tag = str


type LicenseItem = str


type CopyrightItem = str


type Platform = str


type Wheel = str


@dataclass
class Permissions:
    """Resources the add-on requires.

    Each value is a short single-sentence explanation, up to 64
    characters, with no trailing punctuation.
    """

    network: str | None = None
    files: str | None = None
    clipboard: str | None = None
    camera: str | None = None
    microphone: str | None = None


type Path = str


type PathsExcludePatternItem = str


@dataclass
class Build:
    """Advanced build settings used by `blender --command extension build`."""

    paths: list[Path] | None = None
    """File paths (relative to the manifest) to include when building the
    package."""

    paths_exclude_pattern: list[PathsExcludePatternItem] | None = None
    """File-path patterns to exclude when building the package.

    Pattern matching is compatible with gitignore.
    """

@dataclass
class BlenderManifest:
    """Root manifest object serialized as `blender_manifest.toml`."""

    id: str
    """Unique identifier for the extension (snake_case recommended)."""

    version: str
    """Version of the extension.

    Must follow semantic versioning.
    """

    name: str
    """Complete, human-readable name of the extension."""

    tagline: str
    """One-line short description, up to 64 characters.

    Cannot end with punctuation.
    """

    maintainer: str
    """Maintainer of the extension (name and optional contact)."""

    type: Type
    """Extension type."""

    blender_version_min: str
    """Minimum supported Blender version.

    Use at least `4.2.0`.
    """

    license: list[LicenseItem]
    """List of licenses.

    Use SPDX license identifiers prefixed with
    `SPDX:`. See https://spdx.org/licenses/
    """

    schema_version: str = "1.0.0"
    """Internal version of the manifest file format.

    Currently `1.0.0`.
    """

    website: str | None = None
    """Optional link to documentation, support, source files, etc."""

    tags: list[Tag] | None = None
    """Optional tag list defined by Blender.

    See:
    https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
    """

    blender_version_max: str | None = None
    """Blender version that the extension does NOT support; earlier versions
    are supported."""

    copyright: list[CopyrightItem] | None = None
    """Optional, required by some licenses.

    Each entry must be
    `"Year Name"` or `"Year-Year Name"`.
    """

    platforms: list[Platform] | None = None
    """List of supported platforms.

    If omitted, the extension is available on all operating systems.
    Known values: `windows-x64`, `windows-arm64`, `macos-x64`, `macos-
    arm64`, `linux-x64`.
    """

    wheels: list[Wheel] | None = None
    """List of relative file-paths to bundled Python wheels."""

    permissions: Permissions | None = None
    build: Build | None = None
