/* SPDX-FileCopyrightText: 2018-2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file
 * \ingroup intern_clog
 */

#include "CLG_log.h"

/* Add-ons */
CLG_LOGREF_DECLARE_GLOBAL(LOG_ADDON, "addon");

/* Animation & Rigging */
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_ACTION, "anim.action");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_DATA, "anim.data");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_DRIVER, "anim.driver");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_EVALUATION, "anim.evaluation");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_FCURVE, "anim.fcurve");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_FMODIFIER, "anim.fmodifier");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_IPO, "anim.ipo");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_KEYINGSET, "anim.keyingset");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_MOTION_PATH, "anim.motion_path");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ANIM_NLA, "anim.nla");

/* Asset System */
CLG_LOGREF_DECLARE_GLOBAL(LOG_ASSET_CATALOG, "asset.catalog");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ASSET_INDEX, "asset.index");
CLG_LOGREF_DECLARE_GLOBAL(LOG_ASSET_LIBRARY, "asset.library");

/* Blend file read and write */
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND, "blend");
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND_DOVERSION, "blend.doversion");
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND_LINK, "blend.link");
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND_PARTIAL_WRITE, "blend.partial_write");
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND_READFILE, "blend.readfile");
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND_VALIDATE, "blend.validate");
CLG_LOGREF_DECLARE_GLOBAL(LOG_BLEND_WRITEFILE, "blend.writefile");

/* Context */
CLG_LOGREF_DECLARE_GLOBAL(LOG_CONTEXT, "context");

/* Dependency graph */
CLG_LOGREF_DECLARE_GLOBAL(LOG_DEPSGRAPH, "depsgraph");

/* Geometry */
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_ARMATURE_DEFORM, "geom.armature_deform");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_ATTRIBUTE, "geom.attribute");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_BMESH_CONVERT, "geom.bmesh.convert");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_CURVE, "geom.curve");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_CUSTOMDATA, "geom.customdata");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_GPENCIL, "geom.gpencil");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_MESH, "geom.mesh");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_MESH_CONVERT, "geom.mesh.convert");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_VFONT, "geom.vfont");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GEOM_VOLUME, "geom.volume");

/* GPU  */
CLG_LOGREF_DECLARE_GLOBAL(LOG_GPU_DEBUG, "gpu.debug");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GPU_DEBUG_METAL, "gpu.debug.metal");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GPU_PLATFORM, "gpu.platform");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GPU_SHADER, "gpu.shader");
CLG_LOGREF_DECLARE_GLOBAL(LOG_GPU_VULKAN, "gpu.vulkan");

/* Images */
CLG_LOGREF_DECLARE_GLOBAL(LOG_IMAGE, "image");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IMAGE_COLOR_MANAGEMENT, "image.color_management");

/* Import & Export */
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_ALEMBIC, "io.alembic");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_COMMON, "io.common");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_DROP_IMPORT_FILE, "io.drop_import_file");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_FBX, "io.fbx");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_MATERIALX, "io.materialx");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_OBJ, "io.obj");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_PLY, "io.ply");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_STL, "io.stl");
CLG_LOGREF_DECLARE_GLOBAL(LOG_IO_USD, "io.usd");

/* Datablocks and library linking */
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_BPATH, "lib.bpath");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_ICONS, "lib.icons");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_ID_MANAGEMENT, "lib.id_management");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_ID, "lib.id");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_IDPROP, "lib.idprop");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_IDTYPE, "lib.idtype");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_LIBRARY, "lib.library");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_LINK_APPEND, "lib.link_append");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_MAIN_NAMEMAP, "lib.main_namemap");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_MAIN, "lib.main");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_OVERRIDE, "lib.override");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_OVERRIDE_PROXY_CONVERSION, "lib.override.proxy_conversion");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_OVERRIDE_RESYNC, "lib.override.resync");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_PACKEDFILE, "lib.packedfile");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_QUERY, "lib.query");
CLG_LOGREF_DECLARE_GLOBAL(LOG_LIB_REMAP, "lib.remap");

/* RNA */
CLG_LOGREF_DECLARE_GLOBAL(LOG_MAKESRNA, "makesrna");

/* Objects, collections and layers. */
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT, "object");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT_COLLECTION, "object.collection");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT_CONSTRAINT, "object.constraint");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT_DYNAMICPAINT, "object.dynamicpaint");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT_EDIT, "object.edit");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT_LAYER, "object.layer");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OBJECT_MODIFIER, "object.modifier");

/* Editors (when not covered by something else) */
CLG_LOGREF_DECLARE_GLOBAL(LOG_EDITOR_OUTLINER, "editor.outliner");

/* Sculpt & Paint */
CLG_LOGREF_DECLARE_GLOBAL(LOG_PAINT_VERTEX, "paint.vertex");
CLG_LOGREF_DECLARE_GLOBAL(LOG_SCULPT, "sculpt");
CLG_LOGREF_DECLARE_GLOBAL(LOG_SCULPT_BMESH, "sculpt.bmesh");
CLG_LOGREF_DECLARE_GLOBAL(LOG_SCULPT_DETAIL, "sculpt.detail");

/* Physics */
CLG_LOGREF_DECLARE_GLOBAL(LOG_PHYSICS_FLUID, "physics.fluid");
CLG_LOGREF_DECLARE_GLOBAL(LOG_PHYSICS_POINTCACHE, "physics.pointcache");
CLG_LOGREF_DECLARE_GLOBAL(LOG_PHYSICS_RIGIDBODY, "physics.rigidbody");
CLG_LOGREF_DECLARE_GLOBAL(LOG_PHYSICS_SOFTBODY, "physics.softbody");

/* Rendering */
CLG_LOGREF_DECLARE_GLOBAL(LOG_RENDER, "render");
CLG_LOGREF_DECLARE_GLOBAL(LOG_CYCLES, "cycles");

/* Report system */
CLG_LOGREF_DECLARE_GLOBAL(LOG_REPORTS, "reports");

/* RNA */
CLG_LOGREF_DECLARE_GLOBAL(LOG_RNA_ACCESS_COMPARE_OVERRIDE, "rna.access_compare_override");
CLG_LOGREF_DECLARE_GLOBAL(LOG_RNA_ACCESS, "rna.access");
CLG_LOGREF_DECLARE_GLOBAL(LOG_RNA_DEFINE, "rna.define");
CLG_LOGREF_DECLARE_GLOBAL(LOG_RNA_RNA_COMPARE_OVERRIDE, "rna.rna_compare_override");

/* A few datablock that don't fit anywhere else */
CLG_LOGREF_DECLARE_GLOBAL(LOG_MASK, "mask");
CLG_LOGREF_DECLARE_GLOBAL(LOG_MASK_RASTERIZE, "mask.rasterize");
CLG_LOGREF_DECLARE_GLOBAL(LOG_MATERIAL, "material");
CLG_LOGREF_DECLARE_GLOBAL(LOG_NODE, "node");
CLG_LOGREF_DECLARE_GLOBAL(LOG_SOUND, "sound");

/* System functionality */
CLG_LOGREF_DECLARE_GLOBAL(LOG_SYSTEM_PATH, "system.path");

/* Events, operators, tools, msgbus */
CLG_LOGREF_DECLARE_GLOBAL(LOG_EVENTS, "events");
CLG_LOGREF_DECLARE_GLOBAL(LOG_OPERATORS, "operator");
CLG_LOGREF_DECLARE_GLOBAL(LOG_TOOL_GIZMO, "tool.gizmo");
CLG_LOGREF_DECLARE_GLOBAL(LOG_MSGBUS_PUB, "msgbus.pub");
CLG_LOGREF_DECLARE_GLOBAL(LOG_MSGBUS_SUB, "msgbus.sub");

/* Translation */
CLG_LOGREF_DECLARE_GLOBAL(LOG_TRANSLATION, "translation");

/* Undo system */
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO, "undo");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_ARMATURE, "undo.armature");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_CURVE, "undo.curve");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_CURVES, "undo.curves");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_FONT, "undo.font");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_GREASEPENCIL, "undo.greasepencil");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_IMAGE, "undo.image");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_LATTICE, "undo.lattice");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_MBALL, "undo.mball");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_MESH, "undo.mesh");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_PARTICLE, "undo.particle");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_POINTCLOUD, "undo.pointcloud");
CLG_LOGREF_DECLARE_GLOBAL(LOG_UNDO_SCULPT, "undo.sculpt");

/* XR and VR */
CLG_LOGREF_DECLARE_GLOBAL(LOG_XR, "xr");
