//
// T:\blender\source\blender\geometry\intern\fast_math.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern int32_t copy_int_if_compare_float_not(int32_t * values, const float * predicates, const int32_t count, const float min_predicate_value);
    extern void distances(const float positions[][3], const float * target, const int32_t count, float * distances, const float offset);
    extern void distances_split(const float * positions_x, const float * positions_y, const float * positions_z, const float * target, const int32_t count, float * distances, const float offset);
    extern float fixed_safe_0_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_10_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_11_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_12_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_1_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_2_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_3_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_4_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_5_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_6_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_7_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_8_rpow_n(float * values, const int32_t count);
    extern float fixed_safe_9_rpow_n(float * values, const int32_t count);
    extern void float3_dot_product(const float values[][3], const float * factors, const int32_t count, float * result);
    extern void float3_gather_dot_product(const int32_t * indices, const float values[][3], const float * factors, const int32_t count, float * result);
    extern void float3_gather_dot_product_(const int32_t * indices, const float values[][3], const float * factors, const int32_t count, float * result);
    extern float float_dot_product(const float * values, const float * factors, const int32_t count);
    extern float float_gather_dot_product(const int32_t * indices, const float * values, const float * factors, const int32_t count);
    extern void gather_distances(const int32_t * indices, const float positions[][3], const float * target, const int32_t count, float * distances, const float offset);
    extern int32_t one_mul_add_n(float * values, float * factors, const float other, const int32_t count);
    extern int32_t partition_int_compare_float(int32_t * values, int32_t * buffer, const float * predicates, const int32_t count, const float min_predicate_value);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
