//
// T:\blender\source\blender\geometry\intern\fast_math.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern float fixed_pow_0_n(float * values, const int32_t count);
    extern float fixed_pow_10_n(float * values, const int32_t count);
    extern float fixed_pow_11_n(float * values, const int32_t count);
    extern float fixed_pow_12_n(float * values, const int32_t count);
    extern float fixed_pow_1_n(float * values, const int32_t count);
    extern float fixed_pow_2_n(float * values, const int32_t count);
    extern float fixed_pow_3_n(float * values, const int32_t count);
    extern float fixed_pow_4_n(float * values, const int32_t count);
    extern float fixed_pow_5_n(float * values, const int32_t count);
    extern float fixed_pow_6_n(float * values, const int32_t count);
    extern float fixed_pow_7_n(float * values, const int32_t count);
    extern float fixed_pow_8_n(float * values, const int32_t count);
    extern float fixed_pow_9_n(float * values, const int32_t count);
    extern void float3_dot_product(const float values[][3], const float * factors, const int32_t count, float * result);
    extern float float_dot_product(const float * values, const float * factors, const int32_t count);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
