# SPDX-FileCopyrightText: 2025 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

set(HIGHWAY_EXTRA_ARGS
  -DHWY_ENABLE_CONTRIB=OFF
  -DHWY_ENABLE_EXAMPLES=OFF
  -DHWY_ENABLE_INSTALL=ON
  -DHWY_ENABLE_TESTS=OFF
)

ExternalProject_Add(external_highway
  URL file://${PACKAGE_DIR}/${HIGHWAY_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${HIGHWAY_HASH_TYPE}=${HIGHWAY_HASH}
  PREFIX ${BUILD_DIR}/highway
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${LIBDIR}/highway ${DEFAULT_CMAKE_FLAGS} ${HIGHWAY_EXTRA_ARGS}
  INSTALL_DIR ${LIBDIR}/highway
  CMAKE_GENERATOR ${PLATFORM_ALT_GENERATOR}
)
