/* SPDX-FileCopyrightText: 2025 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file
 * \ingroup draw
 */

#ifndef GPU_SHADER
#  pragma once
#endif

#define SKINNING_AABB_LOCAL_SIZE 32

#define SKINNING_LOCAL_SIZE 64

#define SKINNING_DQS_LOCAL_SIZE 64

/* LBS Shader */
/* Uniform buffer bindings */
#define LBS_BONE_ARMATURE_SPACE_BUF_SLOT 3

/* Storage buffer bindings */
#define LBS_INFLUENCE_INDICES_BUF_SLOT 0
#define LBS_INFLUENCE_WEIGHTS_BUF_SLOT 1

#define LBS_BONE_MATRICES_BUF_SLOT 2

#define LBS_BONE_BENDY_BUF_SLOT 4

#define LBS_VERT_POS_BUF_SLOT 5
// #define LBS_VERT_NOR_BUF_SLOT 10
#define LBS_VERT_TAN_BUF_SLOT 6

#define LBS_SKINNED_POS_BUF_SLOT 7
// #define LBS_SKINNED_NOR_BUF_SLOT 6
#define LBS_SKINNED_TAN_BUF_SLOT 8

/* Normals Accumulate buffer bindings */
#define NORMALS_ACCUM_SKINNED_POS_BUF_SLOT 0
#define NORMALS_ACCUM_FACE_ADJACENCY_OFFSETS_BUF_SLOT 1
#define NORMALS_ACCUM_FACE_ADJACENCY_LISTS_BUF_SLOT 2
#define NORMALS_ACCUM_CORNER_VERTS_BUF_SLOT 3
#define NORMALS_ACCUM_VERT_NORMALS_BUF_SLOT 4

/* Normals Finalize buffer bindings */
#define NORMALS_FINAL_SKINNED_POS_BUF_SLOT 0
#define NORMALS_FINAL_VERT_NORMALS_BUF_SLOT 1
#define NORMALS_FINAL_CORNER_VERTS_BUF_SLOT 2
#define NORMALS_FINAL_FACE_OFFSETS_BUF_SLOT 3
#define NORMALS_FINAL_SHARP_FACES_BUF_SLOT 4
#define NORMALS_FINAL_OUT_SKINNED_NOR_BUF_SLOT 5

/* DQS Shader*/
