/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#include <optional>

#include "BLI_array.hh"
#include "BLI_bounds.hh"
#include "BLI_math_vector_types.hh"
#include "BLI_span.hh"

namespace blender::geometry {

/**
 * Can find the polygon/triangle that maps to a specific uv coordinate.
 *
 * \note this uses a trivial implementation currently that has to be replaced.
 */
class ReverseUVSampler {
 public:
  struct LookupGrid;

 private:
  Span<float2> uv_map_;
  Span<int3> corner_tris_;
  Array<float2> centers_;
  float2 resolution_;
  std::unique_ptr<LookupGrid> lookup_grid_;
  int64_t live_count_;

 public:
  ReverseUVSampler(Span<float2> uv_map,
                   Span<int3> corner_tris,
                   std::optional<Bounds<float2>> known_uv_bounds = std::nullopt,
                   std::optional<int64_t> samples_num_hint = std::nullopt);
  ~ReverseUVSampler();

  enum class ResultType {
    None,
    Ok,
    Multiple,
  };

  struct Result {
    ResultType type = ResultType::None;
    int tri_index = -1;
    float3 bary_weights;
  };

  /* `uv_map_override` and `corner_tris_override`: when non-empty, used in place
   * of the Spans passed to the constructor.  This lets a caller cache the
   * sampler (its lookup_grid_ + centers_) across frames while supplying fresh
   * uv_map / corner_tris references each call — the cached Spans would
   * otherwise dangle when the underlying mesh attribute storage is freed or
   * regenerated by the depsgraph.  Callers must guarantee that the override
   * data is content-equivalent to the data passed to the constructor; only the
   * Span identity (pointer + length) is allowed to change. */
  Result sample(const float2 &query_uv,
                Span<float2> uv_map_override = {},
                Span<int3> corner_tris_override = {}) const;
  void sample_many(Span<float2> query_uvs,
                   MutableSpan<Result> r_results,
                   Span<float2> uv_map_override = {},
                   Span<int3> corner_tris_override = {}) const;
};

}  // namespace blender::geometry
