/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#include "types.hh"

namespace lexit {

/* Associates a token type to each ASCII character. */
const unsigned char token_table[128] = {
    /* 0x00, '\0' */ EndOfFile,
    /* 0x01, SOH */ Invalid,
    /* 0x02, STX */ Invalid,
    /* 0x03, ETX */ Invalid,
    /* 0x04, EOT */ Invalid,
    /* 0x05, ENQ */ Invalid,
    /* 0x06, ACK */ Invalid,
    /* 0x07, '\a' */ Invalid,
    /* 0x08, '\b' */ Invalid,
    /* 0x09, '\t' */ Space | Merge,
    /* 0x0A, '\n' */ NewLine,
    /* 0x0B, '\v' */ Invalid,
    /* 0x0C, '\f' */ Invalid,
    /* 0x0D, '\r' */ NewLine,
    /* 0x0E, SO */ Invalid,
    /* 0x0F, SI */ Invalid,
    /* 0x10, DLE */ Invalid,
    /* 0x11, DC1 */ Invalid,
    /* 0x12, DC2 */ Invalid,
    /* 0x13, DC3 */ Invalid,
    /* 0x14, DC4 */ Invalid,
    /* 0x15, NAK */ Invalid,
    /* 0x16, SYN */ Invalid,
    /* 0x17, ETB */ Invalid,
    /* 0x18, CAN */ Invalid,
    /* 0x19, EM */ Invalid,
    /* 0x1A, SUB */ Invalid,
    /* 0x1B, ESC */ Invalid,
    /* 0x1C, FS */ Invalid,
    /* 0x1D, GS */ Invalid,
    /* 0x1E, RS */ Invalid,
    /* 0x1F, US */ Invalid,

    /* 0x20, ' ' */ Space | Merge,
    /* 0x21, '!' */ '!',
    /* 0x22, '"' */ '"',
    /* 0x23, '#' */ '#',
    /* 0x24, '$' */ '$',
    /* 0x25, '%' */ '%',
    /* 0x26, '&' */ '&',
    /* 0x27, '\'' */ '\'',
    /* 0x28, '(' */ '(',
    /* 0x29, ')' */ ')',
    /* 0x2A, '*' */ '*',
    /* 0x2B, '+' */ '+',
    /* 0x2C, ',' */ ',',
    /* 0x2D, '-' */ '-',
    /* 0x2E, '.' */ '.',
    /* 0x2F, '/' */ '/',
    /* 0x30, '0' */ Number | Merge,
    /* 0x31, '1' */ Number | Merge,
    /* 0x32, '2' */ Number | Merge,
    /* 0x33, '3' */ Number | Merge,
    /* 0x34, '4' */ Number | Merge,
    /* 0x35, '5' */ Number | Merge,
    /* 0x36, '6' */ Number | Merge,
    /* 0x37, '7' */ Number | Merge,
    /* 0x38, '8' */ Number | Merge,
    /* 0x39, '9' */ Number | Merge,
    /* 0x3A, ':' */ ':',
    /* 0x3B, ';' */ ';',
    /* 0x3C, '<' */ '<',
    /* 0x3D, '=' */ '=',
    /* 0x3E, '>' */ '>',
    /* 0x3F, '?' */ '?',

    /* 0x40, '@' */ '@',
    /* 0x41, 'A' */ Word | Merge,
    /* 0x42, 'B' */ Word | Merge,
    /* 0x43, 'C' */ Word | Merge,
    /* 0x44, 'D' */ Word | Merge,
    /* 0x45, 'E' */ Word | Merge,
    /* 0x46, 'F' */ Word | Merge,
    /* 0x47, 'G' */ Word | Merge,
    /* 0x48, 'H' */ Word | Merge,
    /* 0x49, 'I' */ Word | Merge,
    /* 0x4A, 'J' */ Word | Merge,
    /* 0x4B, 'K' */ Word | Merge,
    /* 0x4C, 'L' */ Word | Merge,
    /* 0x4D, 'M' */ Word | Merge,
    /* 0x4E, 'N' */ Word | Merge,
    /* 0x4F, 'O' */ Word | Merge,
    /* 0x50, 'P' */ Word | Merge,
    /* 0x51, 'Q' */ Word | Merge,
    /* 0x52, 'R' */ Word | Merge,
    /* 0x53, 'S' */ Word | Merge,
    /* 0x54, 'T' */ Word | Merge,
    /* 0x55, 'U' */ Word | Merge,
    /* 0x56, 'V' */ Word | Merge,
    /* 0x57, 'W' */ Word | Merge,
    /* 0x58, 'X' */ Word | Merge,
    /* 0x59, 'Y' */ Word | Merge,
    /* 0x5A, 'Z' */ Word | Merge,
    /* 0x5B, '[' */ '[',
    /* 0x5C, '\\' */ '\\',
    /* 0x5D, ']' */ ']',
    /* 0x5E, '^' */ '^',
    /* 0x5F, '_' */ Word | Merge,

    /* 0x60, '`' */ '`',
    /* 0x61, 'a' */ Word | Merge,
    /* 0x62, 'b' */ Word | Merge,
    /* 0x63, 'c' */ Word | Merge,
    /* 0x64, 'd' */ Word | Merge,
    /* 0x65, 'e' */ Word | Merge,
    /* 0x66, 'f' */ Word | Merge,
    /* 0x67, 'g' */ Word | Merge,
    /* 0x68, 'h' */ Word | Merge,
    /* 0x69, 'i' */ Word | Merge,
    /* 0x6A, 'j' */ Word | Merge,
    /* 0x6B, 'k' */ Word | Merge,
    /* 0x6C, 'l' */ Word | Merge,
    /* 0x6D, 'm' */ Word | Merge,
    /* 0x6E, 'n' */ Word | Merge,
    /* 0x6F, 'o' */ Word | Merge,
    /* 0x70, 'p' */ Word | Merge,
    /* 0x71, 'q' */ Word | Merge,
    /* 0x72, 'r' */ Word | Merge,
    /* 0x73, 's' */ Word | Merge,
    /* 0x74, 't' */ Word | Merge,
    /* 0x75, 'u' */ Word | Merge,
    /* 0x76, 'v' */ Word | Merge,
    /* 0x77, 'w' */ Word | Merge,
    /* 0x78, 'x' */ Word | Merge,
    /* 0x79, 'y' */ Word | Merge,
    /* 0x7A, 'z' */ Word | Merge,
    /* 0x7B, '{' */ '{',
    /* 0x7C, '|' */ '|',
    /* 0x7D, '}' */ '}',
    /* 0x7E, '~' */ '~',
    /* 0x7F, Del */ Invalid,
};

}  // namespace lexit
