/* SPDX-FileCopyrightText: 2025 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#if defined(WITH_OPENCOLORIO)

#  include "MEM_guardedalloc.h"

#  include "OCIO_gpu_shader_binder.hh"

#  include "../opencolorio.hh"

namespace blender::ocio {

class LibOCIOGPUShaderBinder : public GPUShaderBinder {
 public:
  using GPUShaderBinder::GPUShaderBinder;

  MEM_CXX_CLASS_ALLOC_FUNCS("LibOCIOGPUShaderBinder");

 private:
  /* The source header is added to the generated fragment code before code generated by the
   * processors is added. This allows to easily pass defines to the shader compilation without
   * need to have access to the ShaderCreateInfo.  */
  void construct_shader_for_processors(
      internal::GPUDisplayShader &display_shader,
      OCIO_NAMESPACE::ConstProcessorRcPtr &processor_to_scene_linear,
      OCIO_NAMESPACE::ConstProcessorRcPtr processor_to_display,
      const std::string source_header = "") const;

 protected:
  void construct_display_shader(internal::GPUDisplayShader &display_shader) const override;
  void construct_scene_linear_shader(internal::GPUDisplayShader &display_shader) const override;
};

}  // namespace blender::ocio

#endif
